### ISSUE TITLE
Build the docs is broken for anemoi-training

### ISSUE THREAD

**Issue by anaprietonem** [ecmwf/anemoi-training#161]
### What happened?

The CI action to automatically build the docs generates broken link for the preview of the docs

### What are the steps to reproduce the bug?

Open a PR where there is an update to any file associated to the `docs` that will trigger the action `[readtthedocs-pr-update.yml](https://github.com/ecmwf/anemoi-training/blob/develop/.github/workflows/readtthedocs-pr-update.yml)` and generate a new documentation preview like:

📚 Documentation preview 📚: https://anemoi-training--158.org.readthedocs.build/en/158/

Action uses - https://github.com/readthedocs/actions but there are no recent changes or issues reported
Other anemoi packages seems to be okey. 

### Version

v0.3.0

### Platform (OS and architecture)

ATOS

**Comment by JesperDramsch** [comment]
It's not the CI that is broken but the config for Readthedocs, which doesn't use the correct timezone signifier.


https://readthedocs.org/projects/anemoi-training/builds/26555195/

```
Running Sphinx v8.1.3

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/checkouts/latest/docs/conf.py", line 45, in <module>
    year = datetime.datetime.now(tz="UTC").year
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 496, in build_main
    app = Sphinx(
          ^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 238, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 316, in read
    namespace = eval_config_file(filename, tags)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 542, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/checkouts/latest/docs/conf.py", line 45, in <module>
    year = datetime.datetime.now(tz="UTC").year
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/anemoi-training/checkouts/latest/docs/conf.py", line 45, in <module>
    year = datetime.datetime.now(tz="UTC").year
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
```

**Comment by JesperDramsch** [comment]
This should be fixed before #187 probably.

**Comment by JesperDramsch** [comment]
We could add shields to our Readme:

[![Documentation Status](https://readthedocs.org/projects/anemoi-training/badge/?version=latest)](https://anemoi-training.readthedocs.io/en/latest/?badge=latest)

`[![Documentation Status](https://readthedocs.org/projects/anemoi-training/badge/?version=latest)](https://anemoi-training.readthedocs.io/en/latest/?badge=latest)`
